//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksKuznetsovSmirnov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Rank { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Published { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public Nullable<int> IdOrigLang { get; set; }
        public string PageRange { get; set; }
        public string WordCount { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual OriginalLanguage OriginalLanguage { get; set; }
    }
}
