//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksKuznetsovSmirnov.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BooksKuznetsovSmirnovEntities : DbContext
    {
        public BooksKuznetsovSmirnovEntities()
            : base("name=BooksKuznetsovSmirnovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Books> Books { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<OriginalLanguage> OriginalLanguage { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
